# Data exploration

## Import libraries

In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

## Load the data

In [2]:
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data").is_dir())
raw_data_dir = ROOT / "data" / "raw"

In [3]:
competitions = pd.read_csv(raw_data_dir / "competitions.csv.gz")
clubs = pd.read_csv(raw_data_dir / "clubs.csv.gz")
valuations = pd.read_csv(raw_data_dir / "player_valuations.csv.gz")
players = pd.read_csv(raw_data_dir / "players.csv.gz")
appearances = pd.read_csv(raw_data_dir / "appearances.csv.gz")

## Exploration

In [4]:
competitions.tail(3)

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url
62,UKR1,premier-liga,premier-liga,first_tier,domestic_league,177,Ukraine,UKR1,europa,16.0,https://www.transfermarkt.co.uk/premier-liga/s...
63,UKRP,ukrainian-cup,ukrainian-cup,domestic_cup,domestic_cup,177,Ukraine,UKR1,europa,16.0,https://www.transfermarkt.co.uk/ukrainian-cup/...
64,USC,uefa-super-cup,uefa-super-cup,uefa_super_cup,international_cup,-1,NaN,NaN,europa,NaN,https://www.transfermarkt.co.uk/uefa-super-cup...

In [5]:
clubs.tail(3)

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
793,995,fc-nantes,FC Nantes,FR1,NaN,26,25.1,11,42.3,8,Stade de la Beaujoire,35322,+-0,Luís Castro,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-nantes/star...
794,9961,deportivo-cali,Deportivo Cali,COL1,NaN,28,27.3,4,14.3,1,Estadio Deportivo Cali,52000,+-0,Hernán Torres,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/deportivo-cali...
795,999,nk-istra-1961,NK Istra 1961,KR1,NaN,32,23.4,19,59.4,2,Aldo Drosina,9056,+€3.00m,Goran Tomic,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/nk-istra-1961/...

In [6]:
valuations.tail(3)

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
656298,1155584,2026-06-11,350000,CR Belouizdad,13365,NaN
656299,1044533,2026-06-12,150000,Inter de San Carlos,83197,NaN
656300,1076584,2026-06-12,250000,Gil Vicente U23,99764,NaN

In [7]:
players.tail(3)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
50146,1548905,Iustin,Filote,Iustin Filote,2025,8818,iustin-filote,NaN,NaN,Romania,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/iustin-filote/...,RO1,FC Botosani,NaN,NaN
50147,1550699,Vukasin,Zdravkovic,Vukasin Zdravkovic,2025,7567,vukasin-zdravkovic,NaN,NaN,Serbia,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/vukasin-zdravk...,SER1,FK Radnicki Nis,NaN,NaN
50148,1555760,Aidan,Melville,Aidan Melville,2025,32371,aidan-melville,United States,"Portland, Maine",Puerto Rico,...,NaN,https://img.a.transfermarkt.technology/portrai...,1.0,0.0,17759.0,https://www.transfermarkt.co.uk/aidan-melville...,NaN,NaN,NaN,NaN

In [8]:
appearances.tail(3)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
1894347,4776668_754037,4776668,754037,3563,6890,2026-06-28,Abbosbek Fayzullaev,FIWC,0,0,0,0,73
1894348,4776668_763079,4776668,763079,3563,281,2026-06-28,Abdukodir Khusanov,FIWC,1,0,0,0,90
1894349,4776668_989069,4776668,989069,3563,15300,2026-06-28,Jakhongir Urozov,FIWC,0,0,0,0,82

### Get the Premier League competition ID

In [9]:
competitions.info()

<class 'pandas.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   competition_id        65 non-null     str
 1   competition_code      65 non-null     str
 2   name                  65 non-null     str
 3   sub_type              65 non-null     str
 4   type                  65 non-null     str
 5   country_id            65 non-null     int64
 6   country_name          53 non-null     str
 7   domestic_league_code  53 non-null     str
 8   confederation         65 non-null     str
 9   total_clubs           50 non-null     float64
 10  url                   65 non-null     str
dtypes: float64(1), int64(1), str(9)
memory usage: 5.7 KB

In [10]:
competitions[competitions["country_name"] == "England"][["competition_id", "name", "type"]]

   competition_id              name             type
25            FAC            fa-cup     domestic_cup
29            GB1    premier-league  domestic_league
30           GBCS  community-shield            other

The premier league is identified by the ID GB1

In [11]:
PL_ID = "GB1"

### Get the Premier League appearances

In [12]:
appearances[appearances["competition_id"] == PL_ID].head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
6836,2230140_11680,2230140,11680,1039,631,2012-08-18,Rob Green,GB1,0,0,0,0,90
6837,2230140_13583,2230140,13583,1039,124,2012-08-18,Clint Hill,GB1,0,0,0,0,64
6838,2230140_136589,2230140,136589,1039,1039,2012-08-18,Samba Diakité,GB1,1,0,0,0,86
6839,2230140_14007,2230140,14007,1039,1039,2012-08-18,Shaun Derry,GB1,0,0,0,0,4
6840,2230140_14031,2230140,14031,1039,873,2012-08-18,Andy Johnson,GB1,0,0,0,0,12

We want to focus on the 25/26 season

In [13]:
appearances["date"] = pd.to_datetime(appearances["date"])

In [14]:
appearances[(appearances["competition_id"] == PL_ID)]["date"].max()

Timestamp('2026-05-24 00:00:00')

Last game of the season was on 24 May 2026, so we will filter the appearances to only include those that happened between 1 July 2025 and 24 May 2026.

In [15]:
pl_appearances = appearances[
    (appearances["competition_id"] == PL_ID)
    & (appearances["date"] >= pd.Timestamp("2025-07-01"))
    & (appearances["date"] <= pd.Timestamp("2026-05-24"))
].copy()

pl_appearances.tail()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
1891842,4626177_627626,4626177,627626,399,399,2026-05-24,Wilfried Gnonto,GB1,0,0,0,0,21
1891843,4626177_817665,4626177,817665,379,379,2026-05-24,Pablo,GB1,0,0,0,0,45
1891844,4626177_880245,4626177,880245,379,379,2026-05-24,Mateus Fernandes,GB1,0,0,0,1,90
1891845,4626177_983989,4626177,983989,399,631,2026-05-24,Facundo Buonanotte,GB1,0,0,0,0,12
1891846,4626177_99397,4626177,99397,399,399,2026-05-24,Karl Darlow,GB1,0,0,0,0,90

## Conclusion

- The source has 5 tables: competitions, clubs, players, player valuations and appearances.
- The Premier League is the competition GB1.
- The last Premier League game of the 2025-26 season was played on 24 May 2026: the season goes from 1 July 2025 to this date.
- The next step is to check the quality of the data on this scope (see the data audit notebook).